version: '3'
volumes:
    zabbix-mysql:
services:
    zabbix:
        image: whaleway/zabbix-server-inbuilt-mysql:latest
        ports:
            - "8011:80"
            - "10051:10051"
        cap_add:
            - SYS_RESOURCE
            - SYS_ADMIN
        security_opt:
            - 'apparmor:unconfined'
        volumes:
            - zabbix-mysql:/var/lib/mysql
        tmpfs:
            - /run
            - /sys/fs/cgroup
